baseURL = "www.example.com"
languageCode = "en-us"
title = "Sinvesto Corporation"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.homepage]
  show_call_box = false
  hide_view_all_services = true

  [params.logo]
  mobile = "images/logo/logo-mobile.svg"
  desktop = "images/logo/logo.svg"
  desktop_height = "36px"
  alt = "Serif - A Hugo Business Theme"

  [params.homepage_meta_tags]
  meta_description = "Sinvesto - Smart Financial Investments"
  meta_og_title = "Sinvesto"
  meta_og_type = "Corporate Website"
  meta_og_url = "https://www.sinvesto.com"
  meta_og_description = "Sinvesto - Smart Financial Investments"

  [params.team]
  summary_large_truncate = 120

  [params.footer]
  copyright_text = "All copyrights reserved 2021"

[[menu.main]]

[[menu.main]]
identifier = "lorem-ipsum"
name = "Login"
url = "lorem-ipsum"
weight = 0
parent = "lorem-ipsum"
type = "site_menu_item"

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
